# Generated by Django 5.2.17 on 2026-08-28 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opponent', models.CharField(max_length=100, verbose_name='Соперник')),
                ('tournament', models.CharField(blank=True, max_length=150, verbose_name='Турнир')),
                ('date', models.DateTimeField(verbose_name='Дата и время')),
                ('result', models.CharField(choices=[('win', 'Победа'), ('loss', 'Поражение'), ('upcoming', 'Предстоящий')], default='upcoming', max_length=10, verbose_name='Результат')),
                ('score', models.CharField(blank=True, max_length=20, verbose_name='Счёт')),
            ],
            options={
                'verbose_name': 'Матч',
                'verbose_name_plural': 'Матчи',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=50, verbose_name='Никнейм')),
                ('full_name', models.CharField(blank=True, max_length=100, verbose_name='Настоящее имя')),
                ('role', models.CharField(choices=[('carry', 'Керри'), ('mid', 'Мидер'), ('support', 'Саппорт'), ('offlane', 'Оффлейнер'), ('igl', 'Капитан / IGL'), ('coach', 'Тренер'), ('analyst', 'Аналитик')], max_length=20, verbose_name='Роль')),
                ('avatar', models.ImageField(upload_to='avatars/', verbose_name='Аватар')),
                ('country', models.CharField(blank=True, max_length=50, verbose_name='Страна')),
                ('age', models.PositiveIntegerField(blank=True, null=True, verbose_name='Возраст')),
                ('bio', models.TextField(blank=True, verbose_name='О игроке')),
                ('twitch', models.URLField(blank=True, verbose_name='Twitch')),
                ('twitter', models.URLField(blank=True, verbose_name='Twitter / X')),
                ('discord', models.CharField(blank=True, max_length=50, verbose_name='Discord')),
                ('joined_date', models.DateField(blank=True, null=True, verbose_name='В команде с')),
                ('is_active', models.BooleanField(default=True, verbose_name='В основном составе')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок на странице')),
            ],
            options={
                'verbose_name': 'Игрок',
                'verbose_name_plural': 'Игроки',
                'ordering': ['order', 'nickname'],
            },
        ),
    ]
